import { useLanguageMeta } from './StoreMeta';
import { useCallback } from 'react';
import { get } from 'lodash';

export const EN = {
  cancel: 'Cancel',
  totalNumber: 'Total number',
  asSoonAsPossible: 'Keep your phone online and we will ship the item to you as soon as possible.',
  payYuan: '- get -',
  saveTheOrderNumber: 'It is recommended to save the order number and the mall to facilitate the inquiry of orders.',
  pleaseEnterCorrectVerifyCode: 'Please enter correct verify code',
  offer: 'Offer',
  inventoryShortage: 'Inventory shortage',
  leaveAMessage: 'Leave a message',
  pleaseEnterTheOrderNumber: 'Please enter the order number',
  paymentFailedPleaseTryAgain: 'Payment failed, please try again',
  addComment: 'Add comment',
  freeShippingWhenYouReachTheAmount: 'Free shipping when you reach the amount',
  edit: 'Edit',
  buyAnotherFreeDelivery: 'Buy another $15，free delivery',
  optional: 'Optional：spare phone, product specifications or shipping address, etc.',
  pleaseSelectARatingStar: 'Please select a rating star',
  completed: 'Completed',
  packages: 'Packages',
  pack: 'Package',
  noReview: 'No review',
  customerService: 'Customer service',
  addedToCart: 'Added to cart',
  paymentSuccessful: 'Payment successful',
  items: 'items',
  pleaseEnterYourEmailAddress: 'Please enter your email address',
  quickcheckout: 'Quick checkout',
  asPossible: 'You have an order unpaid, please pay as soon as possible',
  totalPrices: 'Total price',
  recommend: 'Recommend',
  deleteThisShippingAddress: 'Are you sure you want to delete this shipping address?',
  address: 'Address',
  buyMore: 'Buy more',
  thanksForYourReviewKey: 'Thanks for your review, your review will show up after being reviewed',
  confirm: 'Confirm',
  confirmOrder: 'Confirm order',
  stayTt: 'Stay it',
  yourShoppingCartIsEmpty: 'Your shopping bag is empty.',
  closed: 'Closed',
  offlinepayments: 'Offline payments',
  verifyMobileNumber: 'Verify mobile number',
  searchOfGoods: 'Search of goods',
  orderNumber: 'Order number',
  noProductsInthisCategory: 'There are no products in this category.',
  postalCode: 'Postal code',
  productDetails: 'Product details',
  emailAddress: 'Email address',
  replicationFailed: 'Replication failed',
  sevenDayReturns: '7-Day Returns ',
  shortage: 'Inventory shortage',
  notYetClassified: 'Not yet classified',
  details: 'Details',
  patronage: 'Your order has been signed, thank you for your patronage!',
  logisticsNumber: 'Logistics number',
  image: 'Image',
  last: 'Last',
  streetApartmentEtc: 'Street,apartment，etc',
  customerServiceEmail: 'Customer Service Email',
  thePaymentMethodWeProvide: 'The payment method we provide',
  logisticsInformation: 'Logistics information',
  specialNeedsPc: 'Special needs',
  selectAll: 'All',
  phoneNumber: 'Phone number',
  purchased: 'Purchased',
  limitPurchase: 'Limit purchase',
  allOrders: 'All orders',
  pleaseBePatient: 'Order has been shipped, please be patient',
  success: 'Success',
  orderConfirmation: 'Order confirmation',
  name: 'Name',
  receipt: 'The order has been shipped, please pay attention to the receipt!',
  orderNumberOrMobileNumber: 'Please enter your mobile number or order number',
  allComments: 'All comments',
  offerPc: 'Offer',
  friendlyLink: 'Friendly link',
  orderSearch: 'Order search',
  beingConfirmedAndStockingImmediately: 'The order is being confirmed, stocking immediately, please be patient!',
  freightIncluded: 'Freight included',
  choose: 'Choose',
  stockShortage: 'Stock shortage',
  specialNeeds: 'Special needs',
  remove: 'Remove',
  vaildEmail: 'Please enter your vaild email',
  qualityAssurance: 'Quality Assurance',
  commentSuccessful: 'Comment successful',
  successfulCopy: 'Successful copy',
  noDetailsForThisItem: 'There are no details for this item.',
  pleaseReOrderOrContactCustomerService:
    'The order was incorrectly filled due to the receipt of the goods, the audit has not passed, please re-order or contact customer service.',
  deletedSuccessfully: 'Deleted successfully',
  delivery: 'Delivery method',
  mapString: 'Product details',
  yes: 'Yes',
  specification: 'Specification',
  theResult: 'The order is undergoing after-sales processing, please be patient and wait for the result.',
  termsOfService: 'Terms of Service',
  home: 'Home',
  verificationCode: 'Verification code',
  orderDetails: 'Order details',
  customerReview: 'Customer Review',
  orderNotFound: 'Order cannot found, please re-enter',
  similarGoods: 'Similar goods',
  goShopping: 'Go shopping',
  afterSale: 'After sale',
  pleaseEnterPostalCode: 'Please enter Postal code',
  noProducts: 'No products',
  freeDelivery: 'Free delivery',
  productInformation: 'Product information',
  orderNowFreeDelivery: 'Order now can get the free delivery',
  discount: 'Discount',
  fullDiscountOffer: 'Full discount offer',
  confirming: 'Confirming',
  continueShopping: 'Continue shopping',
  deliveryAddress: 'Shipping address',
  orderInvalid: 'Order invalid',
  review: 'Review',
  price: 'Price',
  payment: 'Payment method',
  inquire: 'Inquire',
  item: 'item',
  popularOffersLimitedTimeDiscount: 'Popular offers limited time discount',
  noRelatedProductsKey: 'No related products found',
  orderClosed: 'Order closed',
  morepaymentmethods: 'More payment methods',
  soldOut: 'Sold out',
  logisticsName: 'Logistics name',
  purchaseFailedTryAgain: 'Purchase failed, try refreshing the page',
  shoppingTips: 'Shopping Tips',
  invalid: 'Invalid',
  correctPhoneNumber: 'Please enter the correct phone number',
  productList: 'Product list',
  pageNotFound: 'Page not found',
  totalPrice: 'Original Price',
  afterSalesProcessing: 'After-sales processing',
  minusYuan: '- off for -',
  preparingGoods: 'Preparing goods',
  deleteThisItem: 'Are you sure you want to delete this item?',
  viewMoreComments: 'View more comments',
  pleaseLeaveAMessage: 'Please leave a message.',
  yourOrderWasPlacedSuccessfully: 'Your order was placed successfully',
  freeDeliveryToo: 'Free delivery',
  detailedAddress: 'Address information',
  bePatient: 'Orders are working hard to stock up, please be patient!',
  cancelYourOrder: 'Are you sure you want to cancel your order?',
  shoppingCart: 'Shopping bag',
  addToCart: 'Add to bag',
  copy: 'Copy',
  map: 'Home',
  product: 'Product',
  freeDeliveryFullCourt: 'Free delivery full-court',
  pleaseEnterYourMobileNumber: 'Please enter your mobile number',
  pleaseSelectTheRegion: 'Please select the region',
  searchForGoods: 'Search for goods',
  satisfaction: 'Satisfaction',
  off: '- off for -',
  continueshopping: 'continue shopping',
  successfullyObtained: 'The verification code was successfully obtained.',
  retryAfterSeconds: 'Retry after 5 seconds',
  shippingAddress: 'Please add a shipping address',
  homeDelivery: 'Home delivery',
  complete: 'Complete',
  phoneVerificationCode: 'Please enter your phone verification code',
  pleaseEnterTheCorrectOrderNumber: 'Please enter the correct order number',
  immediatePayment: 'Immediate payment',
  proceedToCheckOut: 'Check out ',
  clickToUpload: 'Click to upload',
  buyNow: 'Buy now',
  orderTime: 'Order time',
  soldOutItems: 'The item you selected contains "sold out" items',
  gotocheckout: 'Go to checkout',
  storePickUp: 'Pick up',
  contactCustomerService: 'Contact with Customer Service',
  selected: 'Selected',
  verification: 'Verification code',
  price1: 'Price',
  orderNumberCantEmpty: 'Order number cannot be empty',
  package: 'Package',
  afterSalesService: 'After-sales service',
  choosePackage: 'Choose package',
  cashOnDelivery: 'Cash on delivery',
  reacquire: 'Reacquire',
  payOrpaid: 'Total price',
  onlinePayments: 'Online payments',
  deleteTheItem: 'Do you want to delete the item?',
  shipped: 'Shipped',
  shippingFee: 'Shipping fee',
  inconvenience: 'The order has been provided for after-sales processing, please forgive us for any inconvenience!',
  yn1: '英文',
  no: 'No',
  productNoexist: 'Product does not exist',
  successfullyadded: 'Successfully added items to the shopping cart',
  addShippingAddress: 'Add shipping address',
  stillNeed: 'Still need',
  leastOneItem: 'Please select at least one item',
  amountReached: 'Amount reached',
  delete: 'Delete',
  operations: 'Operations',
  pleaseEnterYourName: 'Please enter your name',
  atAnyTime: 'Please save this link to check the status of the product at any time.',
  whatYouWantToSay: 'Please enter what you want to say',
  returnCart: 'Return to the bag',
  quantity: 'Quantity',
  productAttributes: 'Please select product attributes',
  pleaseEnterAMessage: 'Please enter a message',
  theOrderHasbeenClosed: 'The order has been closed. Please contact customer service for details.',
};

export const useLanguageFn = () => {
  const language = useLanguageMeta();
  return useCallback(
    key => {
      return get(language, key) || get(EN, key);
    },
    [language],
  );
};
